version: '3.8'

services:
  db:
    image: postgres:15
    container_name: parking-postgres
    environment:
      POSTGRES_USER: parkinguser
      POSTGRES_PASSWORD: parkingpass
      POSTGRES_DB: parkingdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkinguser -d parkingdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: parking-backend
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://db:5432/parkingdb
      QUARKUS_DATASOURCE_USERNAME: parkinguser
      QUARKUS_DATASOURCE_PASSWORD: parkingpass
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
    container_name: parking-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pgdata:
