version: '3.9'

services:
  db:
    image: postgres:15
    container_name: parking-postgres
    environment:
      POSTGRES_DB: parkingdb
      POSTGRES_USER: parkinguser
      POSTGRES_PASSWORD: parkingpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U parkinguser -d parkingdb"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
